# Generated by Django 4.0 on 2023-04-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IceCreamOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(choices=[('ch', 'Chocolate'), ('vn', 'Vanilla'), ('vn', 'VANILLA'), ('cm', 'Chunky Munky')], max_length=2)),
            ],
        ),
    ]
