# Generated by Django 4.0 on 2023-04-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(choices=[('ch', 'Chocolate'), ('vn', 'Vanilla'), ('st', 'Strawberry'), ('cm', 'Chunky Munky')], max_length=2)),
            ],
        ),
    ]
